urls.py
from django.urls import include, path
from . import views

app_name = 'pokemon'
urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:id>/', views.contactor, name='contactor'),
    #path('<int:id>/edit', views.edit, name='edit'),
    path('resource/', views.resource, name='resource'),
    path('profile/', views.profile, name='profile'),
    path('tradelist/', views.tradelist, name='tradelist'),
    path('pokelocator/', views.pokelocator, name='pokelocator'),
    path('profile/maketrade', views.maketrade, name='maketrade'),
    path('offertrade/', views.offertrade, name='offertrade'),
    path('messages/', include('privatemsg.urls', namespace='privatemsg')),
    path('offertrade/<int:post_id>', views.offertrade, name='offertrade'),
    path('notification/', views.notification, name='notification'),
    path('offers/<int:offer_id>', views.sentoffer, name='sentoffer'),

    path('favourite/<int:post_id>', views.favourite, name='favourite')






]

models.py
from django.contrib.postgres.fields import JSONField, ArrayField
from django.db import models
from django.utils import timezone

# Create your models here.

class TradePost(models.Model):
    trader = models.CharField(max_length=200)
    pokemon_name = models.CharField(max_length=200)
    pokemon_id = models.IntegerField()
    pokemon_types = ArrayField(models.CharField(max_length=30), null=True)
    pokemon_abilities = ArrayField(models.CharField(max_length=30), null=True)
    pokemon_level = models.IntegerField(default=1)
    pokemon_gender = models.CharField(max_length=50, default="Male")
    game = models.CharField(max_length=200, default="Red")
    completed_by = models.CharField(max_length=200, default="")
    traded_date = models.DateTimeField(null=True, blank=True)
    deadline = models.DateTimeField()

    def is_active(self):
        return self.traded_date is None and self.deadline >= timezone.now()
        
    def past_expiration(self):
        return self.deadline < timezone.now()

#red
#gottacatchemall

class OfferTrade(models.Model):
    post = models.ForeignKey(TradePost, on_delete=models.CASCADE, default=1)
    trader = models.CharField(max_length=200)
    pokemon_id = models.IntegerField()
    pokemon_name = models.CharField(max_length=200)
    pokemon_types = ArrayField(models.CharField(max_length=30), null=True)
    pokemon_abilities = ArrayField(models.CharField(max_length=30), null=True)
    pokemon_gender = models.CharField(max_length=200, default="Male")
    pokemon_level = models.IntegerField(default=1)
    game = models.CharField(max_length=200)
    state = models.CharField(max_length=20, default="")
    
    def is_available(self):
        return self.state == ""

    def is_accepted(self):
        return self.state == "accepted"

class Pokemon(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)
    types = ArrayField(models.CharField(max_length=30, null=True, blank=True), null=True)
    abilities = ArrayField(models.CharField(max_length=30, null=True, blank=True), null=True)
    # https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#querying-jsonfield
    encounters = JSONField(null=True)

class PokemonTypes(models.Model):
    types = models.CharField(max_length=200)

class Favourite(models.Model):
    post = models.ForeignKey(TradePost, on_delete=models.CASCADE, default=1)
    trader_id  = models.IntegerField()
    trader_name  = models.CharField(max_length=200)

class PokeAbilities(models.Model):
    name = models.CharField(max_length=200)


templates/pokemon/chat.html
{% extends 'pokemon/layout.html' %}
{% block content %}
{% load static %}


{% if user.is_authenticated %}


<div class="container" style="margin-top:100px;margin-bottom:100px;">

    <h1 class="text-primary" style="margin-top:20px;margin-bottom:20px;">Chat</h1>
    <div class="box" style="">
	    <p style="line-height: 2;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst vestibulum. Justo eget magna fermentum iaculis eu non diam. A scelerisque purus semper eget duis. Scelerisque fermentum dui faucibus in ornare. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis. Mattis molestie a iaculis at erat pellentesque. Nisl nisi scelerisque eu ultrices vitae.</p>
</div>




{%else%}
<p> You need an account to proceed </p>
    <a href="/account/login">
    <button class="btn btn-lg btn-secondary">Register or Login</button>
    </a>
{%endif%}
<br>
<br><br>
<br>



{% endblock %}

templates/pokemon/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

templates/pokemon/footer.html
<!doctype html>

{% load static %}


    {% block content %}
    {% endblock %}

    <footer  style="height:100px;background-color:grey;">

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">
        <p style="font-size:14px;color:white;">© 2019 Copyright: CMPT 470 Group 2</p>
       <p style="font-size:14px;color:white;"></p>
       <p style="font-size:14px;color:white;">Pokemon Names and Sprites' trademarks belong to Nintendo and The Pokemon Company.</p>
      </div>
      <!-- Copyright -->

    </footer>

templates/pokemon/index.html
{% extends 'pokemon/layout.html' %}
{% block content %}
{% load static %}


<!-- <img src ="{% static "img/lillie.jpg" %}" alt = "My Image"> -->
<div class="container" width="100%" style="position:relative;top:30px;">
  <img class="img-fluid" src  ="{% static "img/homecover.jpg" %}" alt = "My Image">
</div>

<div class="container" style="margin-top:100px;width:1000px;">

    <h1 class="text-primary">Welcome to Pokemon Marketplace</h1>
	     <p style="line-height: 2; font-size:16px"> This website aims to bring Pokemon trainers
(Pokemon X, Y, Omega Ruby and Alpha Sapphire) and 7th generation Pokemon games
 (Sun and Moon) together in order to complete Wi-Fi trades to gain those elusive
 Pokemon and complete your Pokedex.</p>

 <p style="line-height: 2; font-size:16px">Here you will be able to organise trades with people all
 over the world, but by using website you no longer have to be online hoping someone
 has the Pokemon you are after. Here you are able to find the Pokemon you want,
make an offer, and organise a time to trade without the uncertainty of the Global Trade Station.</p>

  <div class="row" style="margin-top:70px">
  <h4 class="text-primary" style="margin-right:1em">Find your Pokemon</h4>
  <!-- <form action="/pokemon/" method="POST">{% csrf_token %}
    <button class="btn btn-default">
         Reset
    </button>
  </form> -->
  </div>
 <div class="row">
    <div class="form-group col-sm" style="width:200px;display:display:inline-block;">
     <label for="sel1">Pokemon Number</label>
     <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
     <select class="form-control" id="sel1" type="search" name="pkid">
       {% for pkmn in pokemon %}
       <option{% if forloop.counter|title == 1pk.id %} selected{% endif %}>{{forloop.counter}}</option>
       {%endfor%}
     </select>
         <button class="btn btn-default">
            search
         </button>
     </form>
     </div>

     <div class="form-group col-sm" style="width:200px;display:display:inline-block;">
      <label for="sel1">Pokemon Name</label>
      <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
      <select class="form-control" id="sel1" type="search" name="pkname">
        {% for pkmn in pokemon %}
        <option{% if pkmn.name|title == 1pk.name %} selected{% endif %}>{{pkmn.name|title}}</option>
        {%endfor%}
      </select>
          <button class="btn btn-default">
             Search
          </button>
      </form>
      </div>

      <div class="form-group col-sm" style="width:200px;display:inline-block;">
       <label for="sel1">Type</label>
       <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
       <select class="form-control" id="sel1" type="search" name="pktype">
        {% for i in pktype %}
        <option{% if i|title == 1pk.type %} selected{% endif %}>{{ i|title }}</option>
        {%endfor%}
       </select>
           <button class="btn btn-default">
              Search
           </button>
       </form>
       </div>

       <div class="form-group col-sm" style="width:200px;display:inline-block;">
          <label for="sel1">Game</label>
          <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
          <select class="form-control" id="sel1" type="search" name="pkgame">
           {% for i in pkgame %}
             <option{% if i|title == 1pk.game %} selected{% endif %}>{{ i|title }}</option>
           {%endfor%}
          </select>
              <button class="btn btn-default">
                 Search
              </button>
          </form>
          </div>

          <div class="form-group col-sm" style="width:200px;display:inline-block;">
              <label for="sel1">Abilities</label>
              <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
              <select class="form-control" id="sel1" type="search" name="pkability">
               {% for i in pokeabilities %}
                 <option{% if i.name|title == 1pk.ability %} selected{% endif %}>{{ i.name|title }}</option>
               {%endfor%}
              </select>
                  <button class="btn btn-default">
                     Search
                  </button>
              </form>
              </div>

      <!-- <div class="form-group col-sm" style="width:200px;display:inline-block;">
        <label for="sel1">Game</label>
        <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
        <select class="form-control" id="sel1" type="search" name="pkgame">
         {% for i in pkgame %}
           <option{% if i|title == 1pkgame %} selected{% endif %}>{{ i|title }}</option>
         {%endfor%}
        </select>
            <button class="btn btn-default">
               Search
            </button>
        </form>
        </div>

        <div class="form-group col-sm" style="width:200px;display:inline-block;">
        <label for="sel1">Abilities</label>
        <form action="{% url 'pokemon:tradelist' %}" method="POST">{% csrf_token %}
        <select class="form-control" id="sel1" type="search" name="pkability">
         {% for i in pokeabilities %}
           <option{% if i.name|title == 1pkability %} selected{% endif %}>{{ i.name|title }}</option>
         {%endfor%}
        </select>
            <button class="btn btn-default">
               Search
            </button>
        </form>
        </div>-->


   </div>


</div>



<div class="container" style="margin-top:70px;">
    <h1 class="text-primary">How does this work?</h1>
	  <p style="line-height: 2; font-size:16px"> The website has a trading section. Trainers can search for a Pokemon they want. Then,
      the website gives a list of available trade that satisfy the search criteria after pressing the search button.<br>
    The trainer can select a post and make an offer of which Pokemon he/she wants to trade for.<br>
  Once a deal is made, traders can arrange a time on the website's messenger to make a trade through their games</p>



    <a href="/contacts/add_contact">
    </a>
</div>
<div class="container" style="margin-top:70px;">
    <h1 class="text-primary">Closing Trades</h1>
 	    <p style="line-height: 2; font-size:16px"> The following trades are approaching to their deadline. Better make your decision before they are gone
      <br>You may favourite an offer, so you can look back at it from your profile section.<br>
      You must sign-in to your account in order to access the posts</p>
      <br>

      <form action="{% url 'pokemon:index' %}" method="POST">{% csrf_token %}
          <button class="btn btn-default">
              Reset
          </button>
        </form>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Trade #</th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?trader={{toggle.trader}}{{queryString}}">Trader</a></th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?pokemon_offer={{toggle.pokemon_offer}}{{queryString}}">Pkmn Name</a></th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?gender={{toggle.gender}}{{queryString}}">Gender</a></th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?level={{toggle.level}}{{queryString}}">Level</a></th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?game={{toggle.game}}{{queryString}}">Game</a></th>
      <th scope="col"><a href="{% url 'pokemon:index' %}?deadline={{toggle.deadline}}{{queryString}}">Deadline</a></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for trade in tradepost %}
    {% if trade.is_active %}
    <tr>
      <th scope="row">{{trade.id}}</th>
      <td>{{trade.trader}}</td>
      <td><i class="pi pi-{{ trade.pokemon_name|lower }}" style="margin-right:10px;"></i>{{trade.pokemon_name}}</td>
      <td>{{ trade.pokemon_gender }}</td>
      <td>{{ trade.pokemon_level }}</td>
      <td>{{trade.game}}</td>
     <td>{{ trade.deadline }}</td>
     {% if user.username == trade.trader %}
       <td><a href="{% url 'pokemon:offertrade' trade.id %}"><button type="button" class="btn" disabled>Offer</button></a></td>
       <td><button type="button" class="btn" disabled>Favourite</button</td>
     {% else %}
     <td><a href="{% url 'pokemon:offertrade' trade.id %}"><button type="button" class="btn btn-primary" name="offer">Offer</button></a></td>

     <form action="{% url 'pokemon:favourite' trade.id %}" method="GET">
        <td><i class="fa fa-shopping-cart"></i><input type="submit" class="btn btn-primary" value="Favourite" name="favourite"></input></td>
    </form>
    {% endif %}

    </tr>
    {% endif %}
    {% endfor %}



    </tbody>
    </thead>
    </table>




<div class="container" style="margin-top:100px;">
    <h1 class="text-primary">About</h1>
	 <p> This is a website about pokemon. Down below are some random word paragraphs </p>
	    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, s
        ed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercit
        ation ullamco laboris nisi ut aliquip ex ea commodo consequat. d</p>

    <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
       doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
        veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
         ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      sed quia consequuntur magni dolores eos qui ratione voluptatem
      sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,
      consectetur, adipisci velit, sed quia non numquam eius modi tempora
       incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad
       minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam,
        nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit
        qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui
        dolorem eum fugiat quo voluptas nulla pariatur?"
      </p>
    <a href="/contacts/add_contact">
    </a>
</div>
</div>
<br>
<br>
<br>

</body>

{% endblock %}



</html>

templates/pokemon/notification.html
{% extends 'pokemon/layout.html' %}
{% block content %}
{% load static %}


{% if user.is_authenticated %}


<div class="container" style="margin-top:100px;margin-bottom:100px;">

    <h1 class="text-primary" style="margin-top:20px;margin-bottom:20px;">Notification</h1>
    <div class="box" style="">
	    <p style="line-height: 2;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst vestibulum. Justo eget magna fermentum iaculis eu non diam. A scelerisque purus semper eget duis. Scelerisque fermentum dui faucibus in ornare. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis. Mattis molestie a iaculis at erat pellentesque. Nisl nisi scelerisque eu ultrices vitae.</p>
</div>





{%else%}
<p> You need an account to proceed </p>
    <a href="/account/login">
    <button class="btn btn-lg btn-secondary">Register or Login</button>
    </a>
{%endif%}
<br>
<br><br>
<br>



{% endblock %}

templates/pokemon/profile.html
{% extends 'pokemon/layout.html' %}
{% block content %}
{% load static %}

{% if user.is_authenticated %}


<div class="container" style="margin-top:20px;">
<div class="row" style="margin-top:60px;">

  <div class="col-sm" style="position:relative;left:20px;">


   <h1 class="text-primary">Hello, Trainer {{user.username}}</h1>
   <br>

   <!-- <img src ="{% static "img/sun.jpg" %}" style="border-radius:50%;width:40%;"/> -->


    <h4 class="text-primary">Personal Info</h4>

   <p style="font-size:18px;"> User Name: {{user.username}}</p>

   <p style="font-size:18px;">Email: {{user.email}}</p>

   <p style="font-size:18px;">Friend Code: {{fcode}}</p>

</div>

   <div class="col-sm">
      <div class="" style="position:relative;margin-top:90px;">
   <a href="/pokemon/profile/maketrade">
   <button class="btn btn-lg btn-primary">Impose a Trade</button>
   </a>

   <a href="/pokemon/tradelist">
   <button class="btn btn-lg btn-secondary">Visit Trade Post</button>
   </a>

   <a href="/pokemon/pokelocator">
   <button class="btn btn-lg btn-secondary">Visit PokeLocator</button>
   </a>

 </div>

<div class="container" style="margin-top:20px;">



</div>

</div>
</div>

<div class="container" style="margin-top:60px;margin-bottom:20px;">
  <h1 class="text-primary">Received Offers</h1>
  <p>
    You can view the offer that are being sent to you.
  </p>

<div class="container" style="margin-top:20px;">


<table class="table">
 <thead class="thead-light">
    <tr>
      <th scope="col">Offer #</th>
      <th scope="col">Your Pokemon</th>
      <th scope="col">Trader</th>
      <th scope="col">Other Pokemon</th>
      <th scope="col">Level</th>
      <th scope="col">Game</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
 <tbody>
    {% if tradepost %}
      {% for post in tradepost %}
        {% if post.is_active %}
          {% for offer in post.offertrade_set.all %}
            {% if offer.is_available %}

            <tr>
              <th scope="row">{{ offer.pk }}</th>
              <td><i class="pi pi-{{ post.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ post.pokemon_name }}</td>

              <td>{{ offer.trader }}</td>
              <td><i class="pi pi-{{ offer.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ offer.pokemon_name }}</td>
              <td>{{ offer.pokemon_level }}</td>
              <td>{{ post.game }}</td>
              <td><a href="{% url 'pokemon:sentoffer' offer.pk %}"><button type="button" class="btn btn-primary">Go to offer</button></a></form></td>
            </tr>
        
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endfor %}
    {% endif %}
 </tbody>
</table>

</div>
</div>

<div class="container" style="margin-top:60px;margin-bottom:20px;">

    <h1 class="text-primary">Active Offers</h1>
    <p>
      You can view the offer that you have sent.
    </p>

 <div class="container" style="margin-top:20px;">


 <table class="table">
   <thead class="thead-light">
      <tr>
        <th scope="col">Offer #</th>
        <th scope="col">Trader</th>
        <th scope="col">Pokemon Name</th>
        <th scope="col">Level</th>
        <th scope="col">Trade With</th>
        <th scope="col">Other Pokemon</th>
        <th scope="col">Pokemon Level</th>
      </tr>
    </thead>
   <tbody>
        {% for offer in offertrade %}
          {% if offer.is_available %}
            <tr>
              <th scope="row">{{ offer.pk }}</th>
              <td>{{ offer.trader }}</td>
              <td><i class="pi pi-{{ offer.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ offer.pokemon_name }}</td>
              <td>{{ offer.pokemon_level }}</td>
              <td>{{ offer.post.trader }}</td>
              <td><i class="pi pi-{{ offer.post.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ offer.post.pokemon_name }}</td>
              <td>{{ offer.post.pokemon_level }}</td>
            </tr>
          {% endif %}
        {% endfor %}
   </tbody>
 </table>

 </div>
</div>

<div class="container" style="margin-top:60px;margin-bottom:20px;">

    <h1 class="text-primary">Active Trades</h1>
    <p>
      You can view the trade that you have posted.
    </p>

 <div class="container" style="margin-top:20px;">


 <table class="table">
   <thead class="thead-light">
      <tr>
        <th scope="col">Trade #</th>
        <th scope="col">Trader</th>
        <th scope="col">Pkmn Name</th>
        <th scope="col">Level</th>
        <th scope="col">Game</th>
        <th scope="col">Expired by</th>
      </tr>
    </thead>
   <tbody>
      {% if tradepost %}
        {% for post in tradepost %}
          {% if post.is_active %}
            <tr>
              <th scope="row">{{ post.pk }}</th>
              <td>{{ post.trader }}</td>
              <td><i class="pi pi-{{ post.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ post.pokemon_name }}</td>
              <td>{{ post.pokemon_level }}</td>
              <td>{{ post.game }}</td>
              <td>{{ post.deadline }}</td>
            </tr>
          {% endif %}
        {% endfor %}
      {% endif %}
   </tbody>
 </table>

 </div>
</div>

<div class="container" style="margin-top:60px;margin-bottom:20px;">

    <h1 class="text-primary">Past Trades</h1>
	    <p> This website aims to bring Pokemon trainers
(Pokemon X, Y, Omega Ruby and Alpha Sapphire) and 7th generation Pokemon games
 (Sun and Moon) together in order to complete Wi-Fi trades to gain those elusive
 Pokemon and complete your Pokedex.</p>


 <div class="container" style="margin-top:20px;">

 <table class="table">
   <thead class="thead-light">
     <tr>
       <th scope="col">Trade #</th>
       <th scope="col">Original Trader</th>
       <th scope="col">Pokemon Name</th>
       <th scope="col">Level</th>
       <th scope="col">Traded With</th>
       <th scope="col">Traded Pokemon</th>
       <th scope="col">Level</th>
       <th scope="col">Trade Completed</th>

     </tr>
   </thead>
   <tbody>
      {% for post in tradepost %}
        {% if not post.is_active %}
          {% for offer in post.offertrade_set.all %}
            {% if offer.is_accepted %}
            <tr>
              <th scope="row">{{ post.pk }}</th>
              <td>{{ post.trader }}</td>
              <td><i class="pi pi-{{ post.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ post.pokemon_name }}</td>
              <td>{{ post.pokemon_level }}</td>
              <td>{{ offer.trader }}</td>
              <td><i class="pi pi-{{ offer.pokemon_name|lower }}" style="margin-right:10px;"></i>{{ offer.pokemon_name }}</td>
              <td>{{ offer.pokemon_level }}</td>
              <td>{{ post.traded_date }}</td>
            </tr>
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endfor %}
   </tbody>
 </table>

 </div>

</div>

<div class="container" style="margin-top:30px;margin-bottom:100px;">

    <h1 class="text-primary">Favourites</h1>
	    <p> This website aims to bring Pokemon trainers
(Pokemon X, Y, Omega Ruby and Alpha Sapphire) and 7th generation Pokemon games
 (Sun and Moon) together in order to complete Wi-Fi trades to gain those elusive
 Pokemon and complete your Pokedex.</p>

 <div class="container" style="margin-top:20px;">
       <br>

 <table class="table">
   <thead class="thead-light">
     <tr>
       <th scope="col">Trade #</th>
       <th scope="col">Trader</th>
       <th scope="col">Pkmn Name</th>
       <th scope="col">Level</th>
       <th scope="col">Game</th>
       <th scope="col"></th>
       <th scope="col"></th>
     </tr>
   </thead>
   <tbody>
     <tr>

       {% for fav in favourite %}

         <tr>
           <th scope="row">{{ fav.pk }}</th>
           <td>{{ fav.post.trader }}</td>
           <td><i class="pi pi-{{ fav.post.pokemon_name|lower }}" style="margin-right:10px;"></i>{{fav.post.pokemon_name|title}}</td>
           <td>{{ fav.post.pokemon_level }}</td>
           <td>{{ fav.post.game }}</td>
           <td><a href="{% url 'pokemon:offertrade' fav.post.pk %}"><button type="button" class="btn btn-primary" name="offer">Offer</button></a></td>


                <form action="{% url 'pokemon:favourite' fav.pk %}" method="GET">
                   <td><input type="submit" class="btn btn-primary" value="Delete" name="Delete"></input></td>
               </form>
         </tr>

       {% endfor %}



     </tr>
   </tbody>
 </table>

 </div>

</div>

</body>


{%else%}
<div class="container" style="margin-top:200px;margin-bottom:100px;width:1000px;">

  <div class = "row">
   <div class = "col-sm">

     <h1 class="text-primary">Trainer, you have not logged in</h1>
	   <p style="font-size:20px;margin-bottom:60px;">You need an account in order to make trades and contacts with other trainers.</p>


     <a href="/account/login">
            <button class="btn btn-lg btn-primary">Register or Login</button>
     </a>

     <a  href="/pokemon/">
     <button class="btn btn-lg btn-secondary" type="button"
         aria-haspopup="true" aria-expanded="false">
           Cancel
     </button>
     </a>

   </div>

   <div class = "col-sm">

     <div class="container" width="100%" style="position:relative;top:-80px;">
       <img class="img-fluid" src  ="{% static "img/loginpop.jpg" %}" alt = "My Image">
     </div>
    </div>

</div>
{%endif%}

</div>
{% endblock %}

templates/pokemon/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>